/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    locations: Location;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  globals: {};
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface Location {
  id: string;
  name: string;
  address: {
    street: string;
    city: string;
    zipcode: string;
    state: string;
  };
  /**
   * @minItems 2
   * @maxItems 2
   */
  position?: [number, number] | null;
  meetings?:
    | {
        meeting: {
          pathway:
            | "aa"
            | "na"
            | "oa"
            | "talking-circle"
            | "dharma-recovery"
            | "smart-recovery"
            | "celebrate-recovery"
            | "none";
          gender: "coed" | "women" | "men";
          type: "in-person" | "hybrid" | "zoom";
          dayAndTime: {
            dayOfWeek:
              | "monday"
              | "tuesday"
              | "wednesday"
              | "thursday"
              | "friday"
              | "saturday"
              | "sunday";
            timeOnly: string;
          };
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: "users";
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
